services:
  web:
    tty: true
    stdin_open: true
    build:
      context: .
      dockerfile: "Dockerfile.dev"
    command: ['/bin/sh', '-c', 'rm -f tmp/pids/server.pid && bin/dev']
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

volumes:
  postgres_data: